openapi: "3.0.3"
info:
  title: "trade_crossing_server API"
  description: "trade_crossing_server API"
  version: "1.0.0"
servers:
- url: "https://trade_crossing_server"
paths:
  /:
    get:
      description: ""
      responses:
        "200":
          description: "OK"
          content:
            text/plain:
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "Hello World!"
  /user/login:
    get:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/UserLoginRequest"
        required: true
      responses:
        "404":
          description: "Not Found"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "존재하지 않는 유저입니다."
        "200":
          description: "OK <br> Token(accessToken, refreshToken) <br> 응답"
          content:
            '*/*':
              schema:
                type: "object"
  /user/refresh:
    post:
      description: ""
  /user/register:
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/UserRegisterRequest"
        required: true
      responses:
        "500":
          description: "Internal Server Error"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "DB 에러"
        "409":
          description: "Conflict"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "이미 존재하는 유저입니다."
        "417":
          description: "Expectation Failed"
          content:
            '*/*':
              schema:
                type: "string"
              examples:
                Example#1:
                  value: "회원가입 실패"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                type: "object"
components:
  schemas:
    UserLoginRequest:
      type: "object"
      properties:
        snsId:
          type: "string"
        email:
          type: "string"
    UserRegisterRequest:
      type: "object"
      properties:
        snsId:
          type: "string"
        loginMethod:
          type: "string"
          enum:
          - "google"
          - "apple"
        email:
          type: "string"
        userName:
          type: "string"
        islandName:
          type: "string"
        introduction:
          type: "string"