name: trade_crossing_db
services:
  database:
    image: mariadb:latest
    container_name: trade_crossing_db
    ports:
      - "3306:3306"

    # 환경 설정
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: trade_crossing
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
      TZ: Asia/Seoul

    # 볼륨
    volumes:
      - ./db/data:/var/lib/mysql
      # 로그 볼륨 지정
      - ./db/logs:/var/log/mysql

    # 컨테이너 시작 후 실행할 명령어
    command:
      # 캐릭터셋 설정
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_general_ci

      # 로그 설정
      - --general-log=1
      - --general-log-file=/var/log/mysql/general.log