ktor:
  application:
    modules:
      - ukidelly.ApplicationKt.module
  deployment:
    port: 8080
    rootPath: /api/v1
    watch: [ ukidelly ]

server:
  mode: "$mode:dev"

database:
  url: $db_url
  user: $db_user
  password: $db_password

supabase:
  url: "$supabase_url:"
  key: "$supabase_key:"


jwt:
  issuer: "Trade Crossing Ktor Server"
  audience: "Trade Crossing Application"
  realm: "Trade Crossing Ktor Server"
  secret: $jwt_secret



