ktor:
  application:
    modules:
      - ukidelly.ApplicationKt.module
  deployment:
    port: 8080
    rootPath: /api/v1
    watch: [ ukidelly ]

jwt:
  issuer: "Trade Crossing Ktor Server"
  audience: "Trade Crossing Application"
  realm: "Trade Crossing Ktor Server"
  secret: "TradeCrossingKtorServer"

supabase:
  url: "jdbc:postgresql://db.ocxoixsctkhbrfxbppto.supabase.co:5432/postgres"
  username: "postgres"
  password: "wjdrmsdud0922!"

