ktor:
  application:
    modules:
      - ukidelly.ApplicationKt.module
  deployment:
    port: 8080
    rootPath: /api/v1
    watch: [ ukidelly ]

jwt:
  issuer: "https://jwt-provider-domain/"
  audience: "trade-crossing"
  realm: "ktor sample app"
  secret: "Dae Hyeon's first Ktor Project"

mongodb:
  connectionUrl: "mongodb+srv://Ukidelly:x4X9KqHU6QWYGgH7@tradecrossingcluster.jzg8oac.mongodb.net/"
  database: "trade_crossing"


supabase:
  url: "jdbc:postgresql://db.ocxoixsctkhbrfxbppto.supabase.co:5432/postgres"
  username: "postgres"
  password: "oFQurO6HLR5zvLAy"


