ktor:
  development: true
  application:
    modules:
      - ukidelly.ApplicationKt.module
  deployment:
    port: 8080
    rootPath: /api/v1
    watch: [ ukidelly ]


jwt:
  issuer: "Trade Crossing Ktor Server"
  audience: "Trade Crossing Application"
  realm: "Trade Crossing Ktor Server"
  secret: "TradeCrossingKtorServer"

supabase:
  url: "jdbc:postgresql://db.ocxoixsctkhbrfxbppto.supabase.co:5432/postgres"
  username: "postgres"
  password: "wjdrmsdud0922!"

aws:
  dev_url: "jdbc:mysql://trade-crossing-db.c0u8eohuawix.ap-northeast-2.rds.amazonaws.com:3306/trade_crossing_db_dev"
  prod_url: "jdbc:mysql://trade-crossing-db.c0u8eohuawix.ap-northeast-2.rds.amazonaws.com:3306/trade_crossing_db"
  user: "admin"
  password: "wjdrmsdud0922"

server:
  mode: "DEV"
